{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kiosk-data
  labels:
    app.kubernetes.io/name: smart-kiosk
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" }}
  volumeName: {{ .Release.Name }}-kiosk-data-pv
{{- end }}

---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-kiosk-data-pv
  labels:
    app.kubernetes.io/name: smart-kiosk
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | default "1Gi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.storage.hostPath }}
    type: DirectoryOrCreate
{{- end }}
